######################################################################
# Automatically generated by qmake (2.01a) mar. janv. 2 17:15:14 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += 
INCLUDEPATH += .
QT += opengl
QT += widgets

CONFIG +=link_pkgconfig
PKGCONFIG += gtk+-2.0

# Input
HEADERS += cairo.hh Dessin.hh glWidget.h opengl.h Point.hh
SOURCES += cairo.cpp Dessin.cpp glWidget.cpp main.cpp opengl.cpp Point.cpp
